// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ttvoviscvpcchptsnddn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR0dm92aXNjdnBjY2hwdHNuZGRuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM5MTgzOTEsImV4cCI6MjA3OTQ5NDM5MX0._Z6xAgw6Vts62m5r4SqjOANck_ynwZUFs2S4Zq94KQE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});